# fly.toml app configuration file generated for happymusic on 2023-05-27T12:16:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "happymusic"
primary_region = "nrt"

[[services]]
  protocol = "tcp"
  internal_port = 4000

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
