# fly.toml

app = "happymusic"
primary_region = "nrt"

[[services]]
  protocol = "tcp"
  internal_port = 4000

  [[services.ports]]
    handlers = ["http"]
    port = 80  

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
