# fly.toml app configuration file generated for happymusic on 2023-05-27T19:59:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "happymusic"
primary_region = "nrt"



[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0